const nationalityToFlag: Record<string, string> = {
  American: "🇺🇸",
  Argentine: "🇦🇷",
  Australian: "🇦🇺",
  Austrian: "🇦🇹",
  Belgian: "🇧🇪",
  Brazilian: "🇧🇷",
  British: "🇬🇧",
  Canadian: "🇨🇦",
  Chinese: "🇨🇳",
  Colombian: "🇨🇴",
  Czech: "🇨🇿",
  Danish: "🇩🇰",
  Dutch: "🇳🇱",
  Finnish: "🇫🇮",
  French: "🇫🇷",
  German: "🇩🇪",
  Hungarian: "🇭🇺",
  Indian: "🇮🇳",
  Indonesian: "🇮🇩",
  Irish: "🇮🇪",
  Italian: "🇮🇹",
  Japanese: "🇯🇵",
  Malaysian: "🇲🇾",
  Mexican: "🇲🇽",
  Monegasque: "🇲🇨",
  "New Zealander": "🇳🇿",
  Norwegian: "🇳🇴",
  Polish: "🇵🇱",
  Portuguese: "🇵🇹",
  Romanian: "🇷🇴",
  Russian: "🇷🇺",
  "South African": "🇿🇦",
  "South Korean": "🇰🇷",
  Spanish: "🇪🇸",
  Swedish: "🇸🇪",
  Swiss: "🇨🇭",
  Thai: "🇹🇭",
  Turkish: "🇹🇷",
  Venezuelan: "🇻🇪",
}

export function getFlag(nationality?: string): string {
  if (!nationality) return ""
  return nationalityToFlag[nationality] ?? ""
}
